# Uncomment this line to define a global platform for your project
platform :ios, "7.0"

source 'https://github.com/CocoaPods/Specs.git'

target "ApiAIDemo" do

pod 'ApiAI/Core', :path => '../'
pod 'ApiAI/VoiceRequest', :path => '../'
pod 'ApiAI/UIKit', :path => '../'
pod 'ApiAI/ResponseMapping', :path => '../'
pod 'ApiAI/VoiceFileRequest', :path => '../'
pod 'ApiAI/AudioFileConverter', :path => '../'
pod 'MBProgressHUD'

end

