# Uncomment this line to define a global platform for your project
platform :ios, "7.0"

use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

target "ApiAIDemo" do

pod 'ApiAI' #, :path => '../'
pod 'MBProgressHUD'

end

