# Uncomment this line to define a global platform for your project
platform :ios, "7.0"

source 'https://github.com/CocoaPods/Specs.git'

target 'ApiAIDemoSwift' do

pod 'ApiAI', :path => '../'
pod 'ApiAI/UIKit', :path => '../'
pod 'MBProgressHUD'


# build for all architectures 
post_install do |installer| 
    installer.project.targets.each do |target| 
        target.build_configurations.each do |config| 
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO' 
        end 
    end 
end 

end

