# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'APIAiMacOSSwiftDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for APIAiMacOSSwiftDemo
    pod 'ApiAI/Core' 
	pod 'ApiAI/VoiceRequest' 
	pod 'ApiAI/ResponseMapping' 
	pod 'ApiAI/VoiceFileRequest' 

  target 'APIAiMacOSSwiftDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
