# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "OpenAPIDemo" do

pod 'OpenAPI', :path => '../OpenAPI'
pod 'MBProgressHUD'

end

target "OpenAPIDemoTests" do

end

